### ISSUE TITLE
Restructure as composite action with matrix config

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/ottr-reports#43]
I think really we want report-maker.yml action to be a composite action and that's how this needs to be restructured.

Instead of running each we should probably have it like: 

```
  run-check:
    name: Test - ${{ matrix.config.test_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {test_name: "spell_check",   report_path: "check_reports/spell_check_results.tsv", toggle: $inputs.SPELL_TOGGLE}
          - {test_name: "url_check",   report_path: "check_reports/url_check_results.tsv", 
          - toggle: $inputs.URL_TOGGLE}
          - {test_name: "quiz_check",   report_path: "check_reports/quiz_check_results.tsv", toggle: $inputs.CHECK_TOGGLE}
```
Where inputs would be a toggle that would turn the action on or off. 

A big question mark with this approach though is that output in matrix configs like this does get overwritten. But because we save our reports to files this might be okay.
